name: Deploy Hugo Site to Pages

on:
  push:
    branches:
      - main  # Or master, depending on your default branch name

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetches your PaperMod theme
          fetch-depth: 0    # Fetches all history for .GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # This is the secret token provided by Actions, no setup needed
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The repository to deploy to
          external_repository: taskusanakirja/taskusanakirja.github.io
          # The branch in the destination repository
          publish_branch: main
          # The directory to deploy
          publish_dir: ./public
          # The commit message
          commit_message: ${{ github.event.head_commit.message }}
